### ISSUE TITLE
Translate everything into English

### ISSUE THREAD

**Issue by MarvinZeising** [JWDeveloper/JWMeeting#3]
Translate all names of files, variables, methods and everything else into English for more consistency

**Comment by MarvinZeising** [comment]
https://github.com/JWDeveloper/JWMeeting/commit/7cfa46edce324e0237fe5e5c617726083a4cd0a3 https://github.com/JWDeveloper/JWMeeting/commit/abfa1bd567681575729267bb4dd837e669984063

These commits don't work because of the following error: java.lang.NullPointerException
at controller.MainController.initialize(MainController.java:71)

Has anybody an idea? @p-bar

**Comment by p-bar** [comment]
The nullpointer is caused by some naming inconsistencies between MainController and fxml files. Renaming variables in a controller class requires also renaming fx:id attributes in fxml files. Just also rename the views in the fxml files to fix it.
